# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbelt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('text', models.TextField(default='')),
                ('likes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_added', to='pythonbelt.User')),
                ('liked_by_user', models.ManyToManyField(related_name='liked_quotes', to='pythonbelt.User')),
            ],
        ),
    ]
